homeassistant:
  # Name of the location where Home Assistant is running
  name: Via Bosque Pi4
  # Location required to calculate the time the sun rises and sets
  latitude: 35.717954
  longitude: -105.938214
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 2219
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Denver
  
  # Customization file
  customize: !include customize.yaml
    
  whitelist_external_dirs:
  - /tmp
  - /share
  #- /usr/share/hassio/homeassistant

# Enables the frontend
frontend:

# Enables configuration UI
config:

  auth_providers:
   - type: homeassistant

mobile_app:   

# Enable the auth component
#auth:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

hassio:

hacs:
  token: 143b74331bb736f072e7bc3999e86ca5b388c672
  appdaemon: True

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# recorder:
#   db_url: !secret mariadb_url
#   purge_interval: 1
#   purge_keep_days: 7

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

logger:
  default: info
  logs:
    homeassistant.components.shell_command: debug
    homeassistant.components.media_player: error
    homeassistant.components.command_line.switch: warn
    homeassistant.components.service: debug
    custom_components.alexa_media: debug
    alexapy.alexaapi: debug    

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#ios:

notify:
  - name: LarryS
    platform: pushover
    api_key: ae39raeannooa3jwv4zqiede4oo2bo
    user_key: uv7t4utsqjm6g6eorqytdaujw74ovk
  - platform: alexa_media
    name: alexa_media
  - name: loginfo
    platform: syslog
  - name: slomanl75
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 30
    sender: slomanl75@gmail.com
    encryption: starttls
    username: slomanl75
    password: !secret imap_password75
    recipient:
      - raspberrypi275@gmail.com
    sender_name: My Home Assistant    

system_health:
config_check:

device_tracker:
  - platform: iphonedetect
    consider_home: 60
    new_device_defaults:
      track_new_devices: true
    hosts:
      hostone: 192.168.0.14 # Pauls iPhone
      hosttwo: 192.168.0.35 # Larrys iPhone


alexa_media:
  accounts:
    - email: pjrice58@yahoo.com
      password: fastone2013
      url: amazon.com
      scan_interval: 10
      exclude_devices:
        - "This Device"
        - "Paul's Ultimate Ears MEGABOOM"
        - "Paul's Alexa Apps"
        - "Paul's Fire TV stick"
media_player:
  - platform: dlna_dmr
    url: http://192.168.0.16:49152/description.xml
    name: ID4154
  # - platform: samsungtv
  #   host: 192.168.0.24
  #   port: 8002
  #   name: SAMSUNGTV
  #   mac: cc:6e:a4:f8:14:eb
  #   timeout: 20


# zone 1:
#   name: Home
#   latitude: 35.717954
#   longitude: -105.938214
#   icon: mdi:home
#   radius: 159

lutron_caseta:
    host: 192.168.0.5
    keyfile: caseta.key
    certfile: caseta.crt
    ca_certs: caseta-bridge.crt

tuya:
  username: 8182940426
  password: fastsix123
  country_code: '1'
  platform: smart_life

remote:
  - platform: harmony
    name: Master
    host: 192.168.0.13
    scan_interval: 10
    activity: PowerOff
zwave:
  usb_path: /dev/ttyACM0
  

ifttt:
  key: 'r1eGbuDM5YtgxvC5WjGMR'

light:
  - platform: switch
    name: Living Room Table Lamp
    entity_id: switch.012000265ccf7f4a49d4 # Living Room Table Lamp
  - platform: switch    
    name: Living Room Corner Lamp
    entity_id: switch.012000265ccf7f4a3ae7 # living room corner light
  - platform: switch    
    name: Monkey Lamp
    entity_id: switch.01200405ecfabc0f3991 # Monkey Lamp  
  - platform: switch    
    name: Den Lights
    entity_id: switch.002006826001943a20e5 # den lights
  - platform: switch    
    name: Dining room corner light
    entity_id: switch.01200738ecfabc8178d1 # dining room corner light
  - platform: switch    
    name: Master floor lamp
    entity_id: switch.83054848807d3a48b6e5 # Master floor lamp
  - platform: switch    
    name: Bathroom Heat Lamps
    entity_id: switch.master_bathroom_heat_lamp # heat lamps
  - platform: switch
    name: Fireplace Light
    entity_id: switch.01200738ecfabc820947
  - platform: switch
    name: Curio Cabinet
    entity_id: switch.83054848807d3a48b752 # Curio Cabinet     
  - platform: switch
    name: Hearth Light
    entity_id: switch.06007468ecfabc220062 # Hearth Light
  - platform: switch
    name: Garden Uplights
    entity_id: switch.06007468ecfabc220097 # Garden Uplights
sensor:
  - platform: template
    sensors:
      last_alexa:
        entity_id:
          - media_player.paul_s_1st_echo_dot # Living Room
          - media_player.paul_s_2nd_echo_dot # Guest Bedroom
          - media_player.paul_s_new_echo_dot # Master Bedroom
          - media_player.paul_s_2nd_echo_dot_2 # Kitchen 
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
      master:
        value_template: '{{ states.remote.master.attributes.current_activity }}'
        friendly_name: 'Harmony Hub'
      garage_door:
        friendly_name: "Garage Tilt Status"
        value_template: >-
          {% if is_state('sensor.ecolink_garage_door_tilt_sensor_access_control', '22') %}
            Open
          {% else %}
            Closed
          {% endif %}
        icon_template: >-
          {% if is_state('sensor.ecolink_garage_door_tilt_sensor_access_control', '22') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
      speakdiff:
          value_template: >
            '{{ as_timestamp(states("sensor.many_date")) - as_timestamp(states("sensor.speak_date")) }}'

      closet_brightness:
        friendly_name: "Closet Brightness"
        value_template: '{% if states.light.master_closet_lights.attributes.brightness  %}{{
          states.light.master_closet_lights.attributes.brightness }}{% else %}OFF{% endif %}'

  - platform: version

  - platform: imap_email_content
    server: imap.gmail.com
    port: 993
    username: !secret imap_username75
    password: !secret imap_password75
    senders:
      - notifications@nest.com
    scan_interval: 5 
# weather
  - platform: darksky
    api_key: !secret darksky_apikey
    forecast:
      - 0    
    monitored_conditions:
      - icon
      - temperature
      - temperature_high
      - temperature_low
      - humidity

  - platform: imap  # raspberry
    server: imap.gmail.com
    port: 993
    username: !secret imap_username
    password: !secret imap_password
    search: SUBJECT ON

  - platform: file
    name: Many Date
    file_path: /share/many.txt
    scan_interval: 3
  - platform: file
    name: Speak Date
    file_path: /share/speak.txt
    scan_interval: 3    

input_boolean:
  hassio_ready:
    name: Home Assistant Ready(Turn off to reset)
    initial: off
  allowgint:
    name: Allow garage intruder alert
    initial: on
  heatsensor_armed:
    name: Heat Lamp Sensor Armed
    initial: off

switch:
  - platform: command_line
    switches:
      speakcasitatemp_status:
        command_on: "type"
        friendly_name: Announce Casita Temperature
        command_off: "type"    
      speakgarage_status:
        command_on: "type"
        friendly_name: Announce Garage Status
        command_off: "type"        
      red_alert:
        command_on: "type"
        friendly_name: Red Alert
        command_off: "type"
      soundbar_voldn:
        command_on: "type"
        friendly_name: Soundbar Volume Down
        command_off: "type"
      soundbar_volup:
        command_on: "type"
        friendly_name: Soundbar Volume Up
        command_off: "type"
      reboot_rpi:         
        command_on: "/usr/bin/curl -X POST https://maker.ifttt.com/trigger/pulserpi/with/key/dYTmVPZifGPy_YEBf43H3m"
        command_off: "type"
      kitchen_fan20:
        command_on:  "/usr/bin/curl -X POST https://maker.ifttt.com/trigger/fan20percent/with/key/dYTmVPZifGPy_YEBf43H3m"
        command_off:  "/usr/bin/curl -X POST https://maker.ifttt.com/trigger/fanoff/with/key/dYTmVPZifGPy_YEBf43H3m"
      kitchen_fan40:
        command_on:  "/usr/bin/curl -X POST https://maker.ifttt.com/trigger/fan40percent/with/key/dYTmVPZifGPy_YEBf43H3m"
        command_off:  "/usr/bin/curl -X POST https://maker.ifttt.com/trigger/fanoff/with/key/dYTmVPZifGPy_YEBf43H3m"        
      kitchen_fanlight:
        command_on:  "/usr/bin/curl -X POST https://maker.ifttt.com/trigger/fanlighton/with/key/dYTmVPZifGPy_YEBf43H3m"
        command_off:  "/usr/bin/curl -X POST https://maker.ifttt.com/trigger/fanlightoff/with/key/dYTmVPZifGPy_YEBf43H3m"
      cooking:
        command_on: "type"
        friendly_name: Cooking
        command_off: "type"
      emergency:
        command_on: "type"
        friendly_name: Emergency
        command_off: "type"
      open_garage:
        command_on: "type"
        friendly_name: Open Garage Door
        command_off: "type"
      close_garage:
        command_on: "type"
        friendly_name: Close Garage Door
        command_off: "type"
      # insteon_motion:
      #   command_on: "type"
      #   friendly_name: Entry Sensor
      #   command_off: "type" 
      check_config:
        command_on: "type"
        friendly_name: Check Configuration.yaml
        command_off: "type" 

shell_command:
  touch_tts: touch /config/www/tts/dummy.mp3
  remove_old_mp3_files: rm /config/www/tts/*.mp3
  disco_off: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/ttyACM0
  disco_on: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x50" > /dev/ttyACM0
  launch_bbhbat: curl -T bbfile.txt ftp://192.168.0.26:21/ --user pi:fastsix123  
  run_rpurger: curl -T dashfile.txt ftp://192.168.0.26:21/ --user pi:fastsix123
  pingrp: echo "ping" >  /share/pinger.txt
  get_many: grep -i Too.Many home-assistant.log | tail -1 |  cut -d' ' -f 1,2 > /share/many.txt ; 
    grep -i speak.text2 home-assistant.log | tail -1 | cut -d' ' -f 1,2 > /share/speak.txt

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

input_text:
  text2:
    name: Text to Speak to Echo
  text3:
    name: reboot code
    initial: ''
  saved_westdate:
    name: Nest West Saved Date
    initial: ''

input_select:
  sb_source:
    name: Soundbar Audio Source
    options:
     - Echo Dot
     - Bluetooth     
     - IDMusic_4154
     - USB
    initial: Echo Dot
  noises:
    name: SciFi Noises
    options:
      - futuristic_10
      - amzn_sfx_scifi_engines_on_02
      - amzn_sfx_scifi_alarm_04         # Red Alert
      - amzn_sfx_scifi_sheilds_up_01
      - amzn_sfx_scifi_alarm_01
      - zap_01

python_script:

binary_sensor:
  - platform: tod
    name: Closet Bright
    after: sunrise
    before: '23:00'
  - platform: tod
    name: sun minus20
    after: sunset
    after_offset: '-00:30:00'
    before: sunrise
    before_offset: '-00:20:00'
  # - platform: template
  #   sensors:
  #     entry_mot:
  #       friendly_name: "Entry Motion"
  #       value_template: >-
  #         {{ is_state("switch.insteon_motion","on") }}
   
          
#           Bells and Buzzer
# bells: “bell_02”
# buzzer: “buzzers_pistols_01”
# church_bell: “amzn_sfx_church_bell_1x_02”
# doorbell1: “amzn_sfx_doorbell_01”
# doorbell2: “amzn_sfx_doorbell_chime_01”
# doorbell3: “amzn_sfx_doorbell_chime_02”

# Holidays
# xmas_bells: “christmas_05”
# halloween_door: “horror_10”

# Misc
# air_horn: “air_horn_03”
# boing1: “boing_01”
# boing2: “boing_03”
# camera: “camera_01”
# squeaky_door: “squeaky_12”
# ticking_clock: “clock_01”
# trumpet: “amzn_sfx_trumpet_bugle_04”

# Animals
# cat_meow: “amzn_sfx_cat_meow_1x_01”
# dog_bark: “amzn_sfx_dog_med_bark_1x_02”
# lion_roar: “amzn_sfx_lion_roar_02”
# rooster: “amzn_sfx_rooster_crow_01”
# wolf_howl: “amzn_sfx_wolf_howl_02”

# Scifi
# aircraft: “futuristic_10”
# engines: “amzn_sfx_scifi_engines_on_02”
# red_alert: “amzn_sfx_scifi_alarm_04”
# shields: “amzn_sfx_scifi_sheilds_up_01”
# sirens: “amzn_sfx_scifi_alarm_01”
# zap: “zap_01”

# Crowds
# applause: “amzn_sfx_crowd_applause_01”
# cheer: “amzn_sfx_large_crowd_cheer_01”